#!/usr/bin/env csh

if ($?_CONDA_BACKUP_FFLAGS) then
	setenv FFLAGS "${_CONDA_BACKUP_FFLAGS}"
	unsetenv _CONDA_BACKUP_FFLAGS
else
	unsetenv FFLAGS
endif

if ($?_CONDA_BACKUP_FORTRANFLAGS) then
	setenv FORTRANFLAGS "${_CONDA_BACKUP_FORTRANFLAGS}"
	unsetenv _CONDA_BACKUP_FORTRANFLAGS
else
	unsetenv FORTRANFLAGS
endif

if ($?_CONDA_BACKUP_DEBUG_FFLAGS) then
	setenv DEBUG_FFLAGS "${_CONDA_BACKUP_DEBUG_FFLAGS}"
	unsetenv _CONDA_BACKUP_DEBUG_FFLAGS
else
	unsetenv DEBUG_FFLAGS
endif

if ($?_CONDA_BACKUP_DEBUG_FORTRANFLAGS) then
	setenv DEBUG_FORTRANFLAGS "${_CONDA_BACKUP_DEBUG_FORTRANFLAGS}"
	unsetenv _CONDA_BACKUP_DEBUG_FORTRANFLAGS
else
	unsetenv DEBUG_FORTRANFLAGS
endif
