#!/usr/bin/env fish

if set -q _CONDA_BACKUP_FFLAGS
	set -gx FFLAGS "$_CONDA_BACKUP_FFLAGS"
	set -e _CONDA_BACKUP_FFLAGS
else
	set -e FFLAGS
end

if set -q _CONDA_BACKUP_FORTRANFLAGS
	set -gx FORTRANFLAGS "$_CONDA_BACKUP_FORTRANFLAGS"
	set -e _CONDA_BACKUP_FORTRANFLAGS
else
	set -e FORTRANFLAGS
end

if set -q _CONDA_BACKUP_DEBUG_FFLAGS
	set -gx DEBUG_FFLAGS "$_CONDA_BACKUP_DEBUG_FFLAGS"
	set -e _CONDA_BACKUP_DEBUG_FFLAGS
else
	set -e DEBUG_FFLAGS
end

if set -q _CONDA_BACKUP_DEBUG_FORTRANFLAGS
	set -gx DEBUG_FORTRANFLAGS "$_CONDA_BACKUP_DEBUG_FORTRANFLAGS"
	set -e _CONDA_BACKUP_DEBUG_FORTRANFLAGS
else
	set -e DEBUG_FORTRANFLAGS
end
