cmake . ^
-G"NMake Makefiles" ^
-DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
-DJSON_VALIDATOR_SHARED_LIBS=ON ^
-DBUILD_SHARED_LIBS=ON ^
-DJSON_VALIDATOR_BUILD_EXAMPLES=OFF ^
-DJSON_VALIDATOR_BUILD_TESTS=OFF ^
-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE ^
-Bbuildir 

cd buildir
nmake
nmake install
