if ! [[ -z "${DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE}" ]]; then
    export _CONDA_BACKUP_DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE="${DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE}"
fi
if ! [[ -z "${DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT}" ]]; then
    export _CONDA_BACKUP_DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT="${DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT}"
fi

export DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE=true
export DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT=true
