if(NOT CCCL_VERSION_FILE)
    message(FATAL_ERROR "CCCL_VERSION_FILE environment variable is not set.")
else()
    include(${CCCL_VERSION_FILE})
    if(DEFINED CCCL_VERSION_MAJOR AND DEFINED CCCL_VERSION_MINOR AND DEFINED CCCL_VERSION_PATCH)
        execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${CCCL_VERSION_MAJOR}.${CCCL_VERSION_MINOR}.${CCCL_VERSION_PATCH}")
    else()
        message(FATAL_ERROR "CCCL_VERSION components are not defined.")
    endif()
endif()
