if [[ -z "${_CONDA_BACKUP_DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE}" ]]; then
    unset DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE
else
    export DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE="${_CONDA_BACKUP_DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE}"
fi

if [[ -z "${_CONDA_BACKUP_DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT}" ]]; then
    unset DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT
else
    export DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT="${_CONDA_BACKUP_DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT}"
fi
